name: objd_cli
description: The CLI Tool for objD
version: 0.0.1-beta.1
homepage: https://www.stevertus.com
author: Stevertus <stevertusyt@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
 args: 1.5.2
 watcher: 0.9.7+12
 http:  0.12.0+2
executables:
  objd: