name: objd_cli
description: The CLI Tool for objD
version: 0.0.5
homepage: https://objd.stevertus.com
documentation: https://objd.stevertus.com/cli

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  args: ^2.0.0
  watcher: ^1.0.0
  http: ^0.13.1
dev-dependencies:
  pedantic:
executables:
  objd:
