name: objd_cli
description: A sample command-line application.
version: 0.0.1
homepage: https://www.example.com
author: Stevertus <stevertusyt@gmail.com>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
 args: 1.5.2
 watcher: 0.9.7+12

executables:
  objd: