name: objd_cli
description: The CLI Tool for objD
version: 0.0.3
homepage: https://objd.stevertus.com
documentation: https://objd.stevertus.com/cli

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  args: ^1.6.0
  watcher: ^0.9.7+15
  http: ^0.12.2
executables:
  objd:
