name: objd_cli
description: The CLI Tool for objD, create, run and build your projects easily
version: 0.1.1
homepage: https://objd.stevertus.com
documentation: https://objd.stevertus.com/cli

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  args: ^2.3.0
  watcher: ^1.0.1
  http: ^0.13.4
dev_dependencies:
  lints:
executables:
  objd:
